### ISSUE TITLE
Does this editor have an undo command?

### ISSUE THREAD

**Issue by djblue** [Cirru/calcit-editor#68]
I cant find an undo shortcut in https://github.com/Cirru/calcit-editor/wiki/Keyboard-Shortcuts.

**Comment by jiyinyiyong** [comment]
No. Calcit Editor does not have an undo feature since it's putting states on a CLI server and it's not tracking every action/state change.

In Calcit Editor you may reset temp changes, more like git stages. The changed functions are listed in "Files" page and click button then you can reset each definition/ns:

![image](https://user-images.githubusercontent.com/449224/80503610-b1de5000-89a4-11ea-93b5-3b9350ec0152.png)

Also under the expression in "Editor" page, in the status bar, there's a little word `:same`,

![image](https://user-images.githubusercontent.com/449224/80503647-be62a880-89a4-11ea-97ce-1511ff3006a4.png)

after current expression is modified, it's changed to a "Reset" button, so click to reset changes:

![image](https://user-images.githubusercontent.com/449224/80503679-c884a700-89a4-11ea-8107-08324af56f54.png)

I know it's not so convenient as a simple "undo" button. But Calcit Editor does not have a real concept of "text file" like other text editor, and it may be connected with multiple clients. "Undo" is not so simple in this situation.

**Comment by djblue** [comment]
@jiyinyiyong Thanks for the thorough answer!
